package Gui;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import segunda.progra.*;

/**
 *
 * @author Esteban
 */
public class Administrador extends javax.swing.JFrame {

    private Administrador administrador;
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.administrador = new Administrador();
        this.jScrollPane1.setVisible(false);
        this.jScrollPane2.setVisible(false);
        this.LabelPedidos.setVisible(false);
        this.LabelConexiones.setVisible(false);
        this.IP.setVisible(true);
        this.Pedidos.setVisible(true);
        this.observarMejoresProductos.setVisible(false);
        this.observarPeoresProductos.setVisible(false);
        this.observarRelacionPorcentual.setVisible(false);
        this.agregarNuevoProducto.setVisible(false);
        this.modificarProducto.setVisible(false);
        this.observarTodosProductos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        IP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pedidos = new javax.swing.JTable();
        LabelBienvenido = new javax.swing.JLabel();
        LabelConexiones = new javax.swing.JLabel();
        LabelPedidos = new javax.swing.JLabel();
        IniciarSesión = new javax.swing.JButton();
        Administrador = new javax.swing.JTextField();
        LabelAdministrador = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        observarMejoresProductos = new javax.swing.JButton();
        observarPeoresProductos = new javax.swing.JButton();
        observarRelacionPorcentual = new javax.swing.JButton();
        agregarNuevoProducto = new javax.swing.JButton();
        modificarProducto = new javax.swing.JButton();
        observarTodosProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        IP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Dirección IP"
            }
        ));
        this.LabelConexiones.setVisible(false);
        this.LabelPedidos.setVisible(false);
        this.IP.setVisible(false);
        this.Pedidos.setVisible(false);
        jScrollPane1.setViewportView(IP);

        Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Persona", "Número de Teléfono", "Costo ($)", "Dirección", "Cantidad De Productos", "Productos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Pedidos);

        LabelBienvenido.setText("Bienvenido");

        LabelConexiones.setText("Conexiones");

        LabelPedidos.setText("Pedidos");

        IniciarSesión.setText("Iniciar Sesión");
        IniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesiónActionPerformed(evt);
            }
        });

        Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministradorActionPerformed(evt);
            }
        });

        LabelAdministrador.setText("Administrador: ");

        LabelContraseña.setText("Contraseña:");

        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });

        observarMejoresProductos.setText("Observar Mejores Productos");

        observarPeoresProductos.setText("Observar Peores Productos");

        observarRelacionPorcentual.setText("Observar Relación Porcentual");
        observarRelacionPorcentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observarRelacionPorcentualActionPerformed(evt);
            }
        });

        agregarNuevoProducto.setText("Agregar Nuevo Producto");

        modificarProducto.setText("Modificar un Producto");

        observarTodosProductos.setText("Observar Todos Los Productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelConexiones)
                            .addComponent(LabelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IniciarSesión))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(observarMejoresProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(observarTodosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(observarPeoresProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(agregarNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(observarRelacionPorcentual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciarSesión))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConexiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observarRelacionPorcentual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(observarMejoresProductos)
                        .addComponent(observarPeoresProductos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarProducto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregarNuevoProducto)
                        .addComponent(observarTodosProductos)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesiónActionPerformed
        // TODO add your handling code here:
        if(this.LabelAdministrador.isVisible()){
            this.Administrador.setVisible(false);
            this.Contraseña.setVisible(false);
            this.LabelAdministrador.setVisible(false);
            this.LabelContraseña.setVisible(false);
            this.LabelBienvenido.setText("Bienvenido, " + this.Administrador.getText());
            this.LabelPedidos.setVisible(true);
            this.LabelConexiones.setVisible(true);
            this.IniciarSesión.setText("Cerrar Sesión");
            this.jScrollPane1.setVisible(true);
            this.jScrollPane2.setVisible(true);
            this.observarMejoresProductos.setVisible(true);
            this.observarPeoresProductos.setVisible(true);
            this.observarRelacionPorcentual.setVisible(true);
            this.agregarNuevoProducto.setVisible(true);
            this.modificarProducto.setVisible(true);
            this.observarTodosProductos.setVisible(true);
        }
        else{
            this.Administrador.setVisible(true);
            this.Contraseña.setVisible(true);
            this.LabelAdministrador.setVisible(true);
            this.LabelContraseña.setVisible(true);
            this.LabelBienvenido.setText("Bienvenido");
            this.LabelPedidos.setVisible(false);
            this.LabelConexiones.setVisible(false);
            this.IniciarSesión.setText("Iniciar Sesión");
            this.jScrollPane1.setVisible(false);
            this.jScrollPane2.setVisible(false);
            this.observarMejoresProductos.setVisible(false);
            this.observarPeoresProductos.setVisible(false);
            this.observarRelacionPorcentual.setVisible(false);
            this.agregarNuevoProducto.setVisible(false);
            this.modificarProducto.setVisible(false);
            this.observarTodosProductos.setVisible(false);
        }
    }//GEN-LAST:event_IniciarSesiónActionPerformed

    private void AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministradorActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void observarRelacionPorcentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observarRelacionPorcentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observarRelacionPorcentualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Administrador;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTable IP;
    private javax.swing.JButton IniciarSesión;
    private javax.swing.JLabel LabelAdministrador;
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JLabel LabelConexiones;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelPedidos;
    private javax.swing.JTable Pedidos;
    private javax.swing.JButton agregarNuevoProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificarProducto;
    private javax.swing.JButton observarMejoresProductos;
    private javax.swing.JButton observarPeoresProductos;
    private javax.swing.JButton observarRelacionPorcentual;
    private javax.swing.JButton observarTodosProductos;
    // End of variables declaration//GEN-END:variables

}
