package Gui;

import javax.swing.*;
import segunda.progra.Producto;
import segunda.progra.Servidor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Esta es la clase que administrará todos los productos y les dará mantenimiento
 * @author Esteban
 */
public class AgenteProductos extends javax.swing.JFrame {

    private Servidor servidorAModificar;
    private Producto productoAModificar;
    
    /**
     * Crea una nueva ventana utilizando únicamente el servidor, lo que significa que se deseaba agregar un 
     * nuevo producto
     * @param servidorAModificar El servidor que será modificado, al agregarle un nuevo producto
     */
    public AgenteProductos(Servidor servidorAModificar) { 
        initComponents();
        this.servidorAModificar = servidorAModificar;
        this.productoAModificar = null;
    }
    
    /**
     * Crea una nueva ventana utilizando un servidor y un producto, los cuales serán modificados
     * @param servidorAModificar El servidor que será modificado, al modificar uno de sus productos
     * @param productoAModificar El producto que será modificado
     */
    public AgenteProductos(Servidor servidorAModificar, Producto productoAModificar) { 
        initComponents();
        this.servidorAModificar = servidorAModificar;
        this.productoAModificar = productoAModificar;
        //ahora modifico los textos
        this.TextFieldCodigo.setText(productoAModificar.getCodigo());
        //este lo tengo que deshabilitar, ¿no?
        this.TextFieldCodigo.setEnabled(false);
        this.TextFieldCodigo.setEditable(false);
        
        this.TextFieldNombre.setText(productoAModificar.getNombre());
        this.TextAreaDescripcion.setText(productoAModificar.getDescripcion());
        this.jSpinnerCaloriasPieza.setValue(productoAModificar.getCaloriasPieza());
        this.jSpinnerCaloriasPorcion.setValue(productoAModificar.getCaloriasPorcion());
        this.jSpinnerPiezasPorcion.setValue(productoAModificar.getPiezasPorcion());
        this.jSpinnerPrecio.setValue(productoAModificar.getPrecio());
        this.jSpinnerTamanhoPorcion.setValue(productoAModificar.getTamanhoPorcion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        ActualizarCambios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerTamanhoPorcion = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerPiezasPorcion = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerCaloriasPorcion = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerCaloriasPieza = new javax.swing.JSpinner();
        CheckBoxHabilitado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Producto:");

        jSpinnerPrecio.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Precio");

        ActualizarCambios.setText("Actualizar Cambios");
        ActualizarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarCambiosActionPerformed(evt);
            }
        });

        jLabel5.setText("Código del Producto:");

        TextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodigoActionPerformed(evt);
            }
        });

        jLabel6.setText("Descripción del Producto: ");

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextAreaDescripcion);

        jLabel3.setText("Tamaño de la Porción");

        jSpinnerTamanhoPorcion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setText("Piezas Por Porcion");

        jSpinnerPiezasPorcion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel7.setText("Calorias Por Porción");

        jSpinnerCaloriasPorcion.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Calorias Por Pieza");

        jSpinnerCaloriasPieza.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        CheckBoxHabilitado.setText("Habilitado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(CheckBoxHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(TextFieldNombre)
                            .addComponent(TextFieldCodigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerTamanhoPorcion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerPiezasPorcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerCaloriasPorcion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerCaloriasPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(jSpinnerPrecio)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ActualizarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(TextFieldNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerCaloriasPorcion)
                    .addComponent(jSpinnerPiezasPorcion)
                    .addComponent(jSpinnerTamanhoPorcion)
                    .addComponent(jSpinnerPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jSpinnerCaloriasPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(ActualizarCambios)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodigoActionPerformed

    private void ActualizarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarCambiosActionPerformed
        // TODO add your handling code here:
        Producto productoNuevo = new Producto(this.TextFieldCodigo.getText(), this.TextFieldNombre.getText(), this.TextAreaDescripcion.getText(), (int) this.jSpinnerTamanhoPorcion.getValue(), (int)this.jSpinnerPiezasPorcion.getValue(), (int)this.jSpinnerCaloriasPorcion.getValue(), (int)this.jSpinnerCaloriasPieza.getValue(), (int)this.jSpinnerPrecio.getValue());
        if(this.CheckBoxHabilitado.isSelected() != productoNuevo.isHabilitado()){
            productoNuevo.habilitar();
        }
        boolean resultado;
        if(this.productoAModificar != null){
            resultado = this.servidorAModificar.modificarProducto(productoNuevo);
            if(!resultado){
                JOptionPane.showMessageDialog(null, "Hubo un error al modificar el Producto", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Modificación Correcta", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else{
            resultado = this.servidorAModificar.agregarProducto(productoNuevo);
            if(!resultado){
                JOptionPane.showMessageDialog(null, "Hubo un error al crear el producto, puede que ya existiera", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Creación Correcta", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_ActualizarCambiosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarCambios;
    private javax.swing.JCheckBox CheckBoxHabilitado;
    private javax.swing.JTextArea TextAreaDescripcion;
    private javax.swing.JTextField TextFieldCodigo;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCaloriasPieza;
    private javax.swing.JSpinner jSpinnerCaloriasPorcion;
    private javax.swing.JSpinner jSpinnerPiezasPorcion;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JSpinner jSpinnerTamanhoPorcion;
    // End of variables declaration//GEN-END:variables
}
