package Gui;

import segunda.progra.Servidor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import segunda.progra.*;

/**
 *
 * @author Esteban
 */
public class FrameAdministrador extends javax.swing.JFrame {

    private Administrador administrador;
    private HiloActualizador hiloPedidos;
    private HiloActualizador hiloConexiones;
    
    /**
     * Creates new form Administrador
     */
    public FrameAdministrador() {
        initComponents();
        //creo el nuevo administrador desde 0
        this.administrador = null;
        /*
        this.administrador = new Administrador(new Servidor());
        //ahora defino los hilos que actualizarán las tablas de la ventana del administrador
        //por ahora irán aquí, luego de que implemente el login, irán luego del mismo
        this.hiloConexiones = new HiloActualizador(this.administrador.getServidor().getConexiones(), this.IP);
        this.hiloPedidos = new HiloActualizador(this.administrador.getServidor().getPedidos(), this.Pedidos);
        //arranco los 3 hilos que tiene la ventana: los pedidos, conexiones y el más importante, el servidor
        this.hiloConexiones.start();
        this.hiloPedidos.start();
        this.administrador.arrancarServidor();
        */
        //Esto es para que cuando se arranque la ventana, aparezca una sólo el login
        this.setVisibilidadSesion(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        IP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Pedidos = new javax.swing.JTable();
        LabelBienvenido = new javax.swing.JLabel();
        LabelConexiones = new javax.swing.JLabel();
        LabelPedidos = new javax.swing.JLabel();
        IniciarSesión = new javax.swing.JButton();
        Administrador = new javax.swing.JTextField();
        LabelAdministrador = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        observarMejoresProductos = new javax.swing.JButton();
        observarPeoresProductos = new javax.swing.JButton();
        observarRelacionPorcentual = new javax.swing.JButton();
        agregarNuevoProducto = new javax.swing.JButton();
        modificarProducto = new javax.swing.JButton();
        observarTodosProductos = new javax.swing.JButton();
        PorcentajeExpress = new javax.swing.JTextField();
        LabelEmpaque = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        IP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dirección IP Global", "Dirección IP Local", "Tipo de Solicitud"
            }
        ));
        this.LabelConexiones.setVisible(false);
        this.LabelPedidos.setVisible(false);
        this.IP.setVisible(false);
        this.Pedidos.setVisible(false);
        jScrollPane1.setViewportView(IP);

        Pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Persona", "Número de Teléfono", "Precio", "Dirección", "Cantidad De Productos", "Productos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Pedidos);

        LabelBienvenido.setText("Bienvenido");

        LabelConexiones.setText("Conexiones");

        LabelPedidos.setText("Pedidos");

        IniciarSesión.setText("Iniciar Sesión");
        IniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesiónActionPerformed(evt);
            }
        });

        Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministradorActionPerformed(evt);
            }
        });

        LabelAdministrador.setText("Administrador: ");

        LabelContraseña.setText("Contraseña:");

        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });

        observarMejoresProductos.setText("Observar Mejores Productos");

        observarPeoresProductos.setText("Observar Peores Productos");

        observarRelacionPorcentual.setText("Observar Relación Porcentual");
        observarRelacionPorcentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observarRelacionPorcentualActionPerformed(evt);
            }
        });

        agregarNuevoProducto.setText("Agregar Nuevo Producto");

        modificarProducto.setText("Modificar un Producto");

        observarTodosProductos.setText("Observar Todos Los Productos");

        PorcentajeExpress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PorcentajeExpress.setText("15");
        PorcentajeExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorcentajeExpressActionPerformed(evt);
            }
        });

        LabelEmpaque.setText("Porcentaje Empaque:");

        Error.setText("Error al Iniciar Sesión");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelConexiones)
                                    .addComponent(LabelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(IniciarSesión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PorcentajeExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(observarMejoresProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(observarTodosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observarPeoresProductos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarNuevoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(observarRelacionPorcentual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelEmpaque, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PorcentajeExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciarSesión))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelConexiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(observarRelacionPorcentual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(observarPeoresProductos))
                    .addComponent(observarMejoresProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarProducto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregarNuevoProducto)
                        .addComponent(observarTodosProductos)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesiónActionPerformed
        // TODO add your handling code here:
        //¿El administrador es nulo?
        if(this.administrador == null){
            //Debo iniciar sesión
            this.administrador = new Administrador(this.Administrador.getText(), String.valueOf(this.Contraseña.getPassword()));
            if(this.administrador.getNombreUsuario() == null){
                //el inicio de sesión no fue correcto
                this.Error.setVisible(true);
                this.administrador = null;
            }
            else{
                //inicio de sesión correcto, Bienvenido Administrador.
                //Preparo todos los hilos y sistemas correspondientes al administrador conectado
                this.Error.setVisible(false);
                //creo los hilos de actualizaciones
                this.hiloConexiones = new HiloActualizador(this.administrador.getServidor().getConexiones(), this.IP);
                this.hiloPedidos = new HiloActualizador(this.administrador.getServidor().getPedidos(), this.Pedidos);
                //arranco los hilos que tiene la ventana: los pedidos y conexiones
                this.hiloConexiones.start();
                this.hiloPedidos.start();
                //ahora los labels
                this.setVisibilidadSesion(true);
            }
        }
        else{
            //se desea desconectar
            this.administrador.getServidor().pararServidor();
            this.administrador.getServidor().asesinarServidor();
            this.administrador = null;
            this.setVisibilidadSesion(false);
        }
    }//GEN-LAST:event_IniciarSesiónActionPerformed

    private void AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministradorActionPerformed

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void observarRelacionPorcentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observarRelacionPorcentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observarRelacionPorcentualActionPerformed

    private void PorcentajeExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorcentajeExpressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PorcentajeExpressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameAdministrador ventana = new FrameAdministrador();
                ventana.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Administrador;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel Error;
    private javax.swing.JTable IP;
    private javax.swing.JButton IniciarSesión;
    private javax.swing.JLabel LabelAdministrador;
    private javax.swing.JLabel LabelBienvenido;
    private javax.swing.JLabel LabelConexiones;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelEmpaque;
    private javax.swing.JLabel LabelPedidos;
    private javax.swing.JTable Pedidos;
    private javax.swing.JTextField PorcentajeExpress;
    private javax.swing.JButton agregarNuevoProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificarProducto;
    private javax.swing.JButton observarMejoresProductos;
    private javax.swing.JButton observarPeoresProductos;
    private javax.swing.JButton observarRelacionPorcentual;
    private javax.swing.JButton observarTodosProductos;
    // End of variables declaration//GEN-END:variables

    /**
     * Este método esconde los labels y demás componentes típicos de cuando está con sesión iniciada que cuando
     * está con sesión no iniciada
     * @param inicioODesconexion True si se desea que esté con la interfaz conectada, False para desconectada
     */
    private void setVisibilidadSesion(boolean inicioODesconexion){
        if(inicioODesconexion){
            this.Error.setVisible(false);
            this.Administrador.setVisible(false);
            this.Contraseña.setVisible(false);
            this.LabelAdministrador.setVisible(false);
            this.LabelContraseña.setVisible(false);
            this.LabelBienvenido.setText("Bienvenido, " + this.administrador.getNombreUsuario());
            this.LabelEmpaque.setVisible(true);
            this.PorcentajeExpress.setVisible(true);
            this.LabelPedidos.setVisible(true);
            this.LabelConexiones.setVisible(true);
            this.IniciarSesión.setText("Cerrar Sesión");
            this.IP.setVisible(true);
            this.Pedidos.setVisible(true);
            this.jScrollPane1.setVisible(true);
            this.jScrollPane2.setVisible(true);
            this.observarMejoresProductos.setVisible(true);
            this.observarPeoresProductos.setVisible(true);
            this.observarRelacionPorcentual.setVisible(true);
            this.agregarNuevoProducto.setVisible(true);
            this.modificarProducto.setVisible(true);
            this.observarTodosProductos.setVisible(true);
        }
        else{
            this.Error.setVisible(false);
            this.Administrador.setVisible(true);
            this.Contraseña.setVisible(true);
            this.LabelAdministrador.setVisible(true);
            this.LabelContraseña.setVisible(true);
            this.LabelBienvenido.setText("Bienvenido");
            this.LabelEmpaque.setVisible(false);
            this.PorcentajeExpress.setVisible(false);
            this.LabelPedidos.setVisible(false);
            this.LabelConexiones.setVisible(false);
            this.IniciarSesión.setText("Iniciar Sesión");
            this.IP.setVisible(false);
            this.Pedidos.setVisible(false);
            this.jScrollPane1.setVisible(false);
            this.jScrollPane2.setVisible(false);
            this.observarMejoresProductos.setVisible(false);
            this.observarPeoresProductos.setVisible(false);
            this.observarRelacionPorcentual.setVisible(false);
            this.agregarNuevoProducto.setVisible(false);
            this.modificarProducto.setVisible(false);
            this.observarTodosProductos.setVisible(false);
        }
    }
}
